
# 应用配置
spring:
  application:
    name:  spring-sample
    instance_id: 127.0.0.1
  config:
    location: classpath:/,classpath:/conf/,file:./,file:../conf/
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 服务配置
server:
  port: 9999
  connection-timeout: 5000
  compression:
    enabled: true
    mime-types:
      - application/json
    min-response-size: 4096
  tomcat:
    accept-count: 500
    min-spare-threads: 10
    max-threads: 3000
    max-connections: 10000
    basedir: /usr/local/tomcat/base/${spring.application.name}

# 日志路径配置
logging.file: /var/log/apollo/${spring.application.name}/${spring.application.name}.log
logging:
  file:
    max-history: 10
    max-size: 50MB
  level:
    root: INFO

# mybatis扫描包路径
mybatis:
  type-aliases-package: com.alonelyleaf.spring.mybatis
  configuration:
    map-underscore-to-camel-case: true #驼峰转化
    # 打印sql, 方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100

# 数据库配置及连接池配置
# 配置连接池，HikariCP 或 Druid https://blog.csdn.net/varyall/article/details/87916767
# com.mysql.jdbc.Driver 和 com.mysql.cj.jdbc.Driver的区别 serverTimezone设定 https://blog.csdn.net/superdangbo/article/details/78732700
spring.datasource:
  url: jdbc:mysql://10.200.112.180:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  username: root
  password: mysql123
  driver-class-name: com.mysql.cj.jdbc.Driver
  continue-on-error: true
  sql-script-encoding: UTF-8
  type: com.alibaba.druid.pool.DruidDataSource

spring.druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    # 间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    # 一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    use-global-data-source-stat: true
    filters: stat,wall,log4j2

# Redis数据库索引（默认为0）
spring.redis.database: 0
# Redis服务器地址
spring.redis.host: localhost
# Redis服务器连接端口
spring.redis.port: 6379
# Redis服务器连接密码（默认为空）
spring.redis.password:
# 连接池最大连接数（使用负值表示没有限制） 默认 8
spring.redis.lettuce.pool.max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
spring.redis.lettuce.pool.max-wait: -1
# 连接池中的最大空闲连接 默认 8
spring.redis.lettuce.pool.max-idle: 8
# 连接池中的最小空闲连接 默认 0
spring.redis.lettuce.pool.min-idle: 0

#-----------------start spring cloud netflix config---------------------

#ribbon配置 see more：com.netflix.client.config.DefaultClientConfigImpl
ribbon:
  # 启用okhttp
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  ConnectTimeout: 5000
  ReadTimeout: 30000
  MaxConnectionsPerHost: 200 #每个节点的最大连接数 默认值50
  MaxTotalConnections: 2000 # 总连接数 默认值200
  PoolMinThreads: 5 #线程池最小容量 默认值1 值范围1-10
  PoolMaxThreads: 300 #线程池最大容量 默认值 200 值范围200-400

#feign配置
feign:
  # 启用okhttp
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  compression:
    response:
      enabled: true
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 4096

#断路器配置
hystrix:
  command:
    default:
      circuitBreaker:
        # 关闭断路器
        enable: false
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            # 断路器处理的超时时间 (毫秒), 大于等于 ribbon 总超时时间
            # timeoutInMilliseconds > (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1)
            timeoutInMilliseconds: 35000
  threadpool:
    default:
      # 核心线程数
      coreSize: 100
      # 最大线程数
      maximumSize: 2000


microservice.rss.manager.host:


# 频率控制配置
ratelimit.config:
  sync: 100
  batchSync: 100
#-----------------end spring cloud netflix config---------------------

